repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
  - repo: https://github.com/sco1/flake8-annotations
    rev: 3.1.1
    hooks:
      - id: flake8-annotations
